services:
  postgres:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - guidata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  guidata:
    external: true